version: '2.3'
services:
  cloud_film:
    image: hub.infervision.com/dev/film:0.0.1
    environment:
      - REPACS_URL=http://192.168.109.92:3333
      - FS_URL=http://192.168.109.92:8000
      - VIEWER_URL=http://192.168.110.123:3000
    volumes:
      - ./film_logs/:/app/logs/
      - /media/tx-deepocean/Data/:/media/tx-deepocean/Data/
    ports:
      - 5000:3302
    restart: always


